name: logistic_management
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #State Management
  provider: ^6.1.5
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1

  #Web Services
  http: ^1.4.0
  flutter_background_service: ^5.1.0

  #UI Pubs
  syncfusion_flutter_charts: ^30.1.41
  syncfusion_flutter_signaturepad: ^30.2.5
  excel: ^4.0.6
  csv: ^6.0.0
  spreadsheet_decoder: ^2.3.0
  google_maps_flutter: ^2.12.3
  flutter_polyline_points: ^3.0.1
  collection: ^1.19.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  url_launcher: ^6.3.2
  timeline_tile: ^2.0.0
  package_info_plus: ^8.0.3
  badges: ^3.1.2
  geolocator: ^14.0.2
  file_picker: ^10.3.2
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.4.1
  #Databases
  shared_preferences: ^2.5.3
  firebase_core: ^4.0.0
  firebase_database: ^12.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/driver1.jpg
    - assets/driver2.jpg
    - assets/default_driver.png
    - assets/licence1.jpg
    - assets/licence2.jpg
    - assets/photo1.jpg
    - assets/photo2.jpg
    - assets/photo3.jpg
    - assets/photo4.jpg
    - assets/proof_photo.jpg
    - assets/proof_signature.png
    - assets/google_map.png
    - assets/waze.png
    - shorebird.yaml
